### PR TITLE
P andreew loop fixed

### PR DESCRIPTION
**Pull request by PAndreew**
Fixed the following:
- loop stopped after first page
- LinkedIn now displays the search results in a separate scrollable <div> on the left side of the page; we shall scroll to its bottom

### CODE REVIEW

**Review by krapes — CHANGES_REQUESTED** [review]
I ran your branch and it looks good :D

pending the print statement change we are approved!

**Comment by PAndreew** [comment]
@krapes By "[0]" do you refer to for example "uploads[0].keys"? "uploads" returned a list for me and therefore "keys" dropped an error. Maybe I'm missing something?

**Comment by krapes** [comment]
@PAndreew 
Yup, exactly. I was referring to the `[0]` in `uploads[0].keys`.

I believe "uploads" returned a list for you because the way the `config.yaml` file was written. If the Uploads section of the file contains a  dash (`"-"`) then the parser will return a list. See example below:
```
uploads:
- Photo: "my/file/path"

# This returns a list
```

If however the dash (`"-"`) is not present the Uploads section will  return a dictionary. See example below:
```
uploads:
  Photo: "my/file/path"

# This returns a dictionary
```

In this case we've established that we want option 2 (the dictionary) in an attempt to make the code cleaner and more readable.

**Review by krapes — APPROVED** [review]

**Comment by krapes** [comment]
@PAndreew  Thanks!

**Comment by PAndreew** [comment]
@krapes You were right, I've removed the indexing. I didn't want to change the Readme file, but maybe this info (i.e. do not use '-' for listing the Uploads) would be useful.

**Pull request merged**
